### 2018 popular programming language
- https://www.kdnuggets.com/2018/05/poll-tools-analytics-data-science-machine-learning-results.html
- https://spectrum.ieee.org/at-work/innovation/the-2018-top-programming-languages

### R vs Python
- https://www.datacamp.com/community/tutorials/r-or-python-for-data-analysis

In [3]:
help(package = 'base')

In [4]:
?sum

In [8]:
sum(c(1,2,3,NA),na.rm = T)

[1] 6

In [9]:
?base::sum

In [10]:
help.search("sum")

In [11]:
??sum

In [13]:
data('iris')

In [14]:
ls()

[1] "iris"

In [15]:
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
⋮   ⋮            ⋮           ⋮            ⋮           ⋮        
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [16]:
rm(iris)

In [17]:
ls()

character(0)

In [18]:
data(iris)

In [19]:
iris

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
⋮   ⋮            ⋮           ⋮            ⋮           ⋮        
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [20]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


In [21]:
class(iris)

[1] "data.frame"

In [23]:
class(1.3)

[1] "numeric"

In [24]:
1L

[1] 1

In [26]:
class(3L)

[1] "integer"

In [28]:
class('aaa')

[1] "character"

In [29]:
class("aaa")

[1] "character"

In [30]:
TRUE

[1] TRUE

In [31]:
T

[1] TRUE

In [32]:
TRUE == T

[1] TRUE

In [33]:
class(TRUE)

[1] "logical"

In [35]:
class(1+4i)

[1] "complex"

In [39]:
dt = '2018/05/01'

In [40]:
class(dt)

[1] "character"

In [41]:
as.Date(dt,format = '%Y/%m/%d')

[1] "2018-05-01"

In [42]:
class( as.Date(dt,format = '%Y/%m/%d') )

[1] "Date"

In [43]:
3+8

[1] 11

In [44]:
3-8

[1] -5

In [45]:
3

[1] 3

In [47]:
c(3) == 3

[1] TRUE

In [48]:
2^10

[1] 1024

In [49]:
11%%2

[1] 1

In [50]:
x <- 3

In [51]:
x

[1] 3

In [52]:
x = 5

In [53]:
x

[1] 5

In [56]:
assign("x",3)

In [57]:
x

[1] 3

In [59]:
height_vec = c(156,198,147,165)

In [60]:
height_vec

[1] 156 198 147 165

In [61]:
matrix(height_vec,byrow=T,nrow=2)

[,1] [,2]
[1,] 156  198 
[2,] 147  165

In [63]:
factor(c('A','AB','O','A'))

[1] A  AB O  A 
Levels: A AB O

In [65]:
str(iris)

'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...


In [66]:
iris$Species

[1] setosa     setosa     setosa     setosa     setosa     setosa    
  [7] setosa     setosa     setosa     setosa     setosa     setosa    
 [13] setosa     setosa     setosa     setosa     setosa     setosa    
 [19] setosa     setosa     setosa     setosa     setosa     setosa    
 [25] setosa     setosa     setosa     setosa     setosa     setosa    
 [31] setosa     setosa     setosa     setosa     setosa     setosa    
 [37] setosa     setosa     setosa     setosa     setosa     setosa    
 [43] setosa     setosa     setosa     setosa     setosa     setosa    
 [49] setosa     setosa     versicolor versicolor versicolor versicolor
 [55] versicolor versicolor versicolor versicolor versicolor versicolor
 [61] versicolor versicolor versicolor versicolor versicolor versicolor
 [67] versicolor versicolor versicolor versicolor versicolor versicolor
 [73] versicolor versicolor versicolor versicolor versicolor versicolor
 [79] versicolor versicolor versicolor versicolor versicolor versicolor
 [85] versicolor versicolor versicolor versicolor versicolor versicolor
 [91] versicolor versicolor versicolor versicolor versicolor versicolor
 [97] versicolor versicolor versicolor versicolor virginica  virginica 
[103] virginica  virginica  virginica  virginica  virginica  virginica 
[109] virginica  virginica  virginica  virginica  virginica  virginica 
[115] virginica  virginica  virginica  virginica  virginica  virginica 
[121] virginica  virginica  virginica  virginica  virginica  virginica 
[127] virginica  virginica  virginica  virginica  virginica  virginica 
[133] virginica  virginica  virginica  virginica  virginica  virginica 
[139] virginica  virginica  virginica  virginica  virginica  virginica 
[145] virginica  virginica  virginica  virginica  virginica  virginica 
Levels: setosa versicolor virginica

In [67]:
iris$Sepal.Length

[1] 5.1 4.9 4.7 4.6 5.0 5.4 4.6 5.0 4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 [19] 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.0 5.0 5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.0
 [37] 5.5 4.9 4.4 5.1 5.0 4.5 4.4 5.0 5.1 4.8 5.1 4.6 5.3 5.0 7.0 6.4 6.9 5.5
 [55] 6.5 5.7 6.3 4.9 6.6 5.2 5.0 5.9 6.0 6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 [73] 6.3 6.1 6.4 6.6 6.8 6.7 6.0 5.7 5.5 5.5 5.8 6.0 5.4 6.0 6.7 6.3 5.6 5.5
 [91] 5.5 6.1 5.8 5.0 5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
[109] 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.0 6.9 5.6 7.7 6.3 6.7 7.2
[127] 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.0 6.9 6.7 6.9 5.8 6.8
[145] 6.7 6.7 6.3 6.5 6.2 5.9

In [73]:
li = list(x=3,y='aaa',z=iris)

In [69]:
list(3,"y")

[[1]]
[1] 3

[[2]]
[1] "y"

In [71]:
li$x

[1] 3

In [72]:
li$y

[1] "aaa"

In [74]:
li$z

Sepal.Length Sepal.Width Petal.Length Petal.Width Species  
1   5.1          3.5         1.4          0.2         setosa   
2   4.9          3.0         1.4          0.2         setosa   
3   4.7          3.2         1.3          0.2         setosa   
4   4.6          3.1         1.5          0.2         setosa   
5   5.0          3.6         1.4          0.2         setosa   
6   5.4          3.9         1.7          0.4         setosa   
7   4.6          3.4         1.4          0.3         setosa   
8   5.0          3.4         1.5          0.2         setosa   
9   4.4          2.9         1.4          0.2         setosa   
10  4.9          3.1         1.5          0.1         setosa   
11  5.4          3.7         1.5          0.2         setosa   
12  4.8          3.4         1.6          0.2         setosa   
13  4.8          3.0         1.4          0.1         setosa   
14  4.3          3.0         1.1          0.1         setosa   
15  5.8          4.0         1.2          0.2         setosa   
16  5.7          4.4         1.5          0.4         setosa   
17  5.4          3.9         1.3          0.4         setosa   
18  5.1          3.5         1.4          0.3         setosa   
19  5.7          3.8         1.7          0.3         setosa   
20  5.1          3.8         1.5          0.3         setosa   
21  5.4          3.4         1.7          0.2         setosa   
22  5.1          3.7         1.5          0.4         setosa   
23  4.6          3.6         1.0          0.2         setosa   
24  5.1          3.3         1.7          0.5         setosa   
25  4.8          3.4         1.9          0.2         setosa   
26  5.0          3.0         1.6          0.2         setosa   
27  5.0          3.4         1.6          0.4         setosa   
28  5.2          3.5         1.5          0.2         setosa   
29  5.2          3.4         1.4          0.2         setosa   
30  4.7          3.2         1.6          0.2         setosa   
⋮   ⋮            ⋮           ⋮            ⋮           ⋮        
121 6.9          3.2         5.7          2.3         virginica
122 5.6          2.8         4.9          2.0         virginica
123 7.7          2.8         6.7          2.0         virginica
124 6.3          2.7         4.9          1.8         virginica
125 6.7          3.3         5.7          2.1         virginica
126 7.2          3.2         6.0          1.8         virginica
127 6.2          2.8         4.8          1.8         virginica
128 6.1          3.0         4.9          1.8         virginica
129 6.4          2.8         5.6          2.1         virginica
130 7.2          3.0         5.8          1.6         virginica
131 7.4          2.8         6.1          1.9         virginica
132 7.9          3.8         6.4          2.0         virginica
133 6.4          2.8         5.6          2.2         virginica
134 6.3          2.8         5.1          1.5         virginica
135 6.1          2.6         5.6          1.4         virginica
136 7.7          3.0         6.1          2.3         virginica
137 6.3          3.4         5.6          2.4         virginica
138 6.4          3.1         5.5          1.8         virginica
139 6.0          3.0         4.8          1.8         virginica
140 6.9          3.1         5.4          2.1         virginica
141 6.7          3.1         5.6          2.4         virginica
142 6.9          3.1         5.1          2.3         virginica
143 5.8          2.7         5.1          1.9         virginica
144 6.8          3.2         5.9          2.3         virginica
145 6.7          3.3         5.7          2.5         virginica
146 6.7          3.0         5.2          2.3         virginica
147 6.3          2.5         5.0          1.9         virginica
148 6.5          3.0         5.2          2.0         virginica
149 6.2          3.4         5.4          2.3         virginica
150 5.9          3.0         5.1          1.8         virginica

In [76]:
numeric(5)

[1] 0 0 0 0 0

In [77]:
class(numeric(5))

[1] "numeric"

In [78]:
integer(5)

[1] 0 0 0 0 0

In [79]:
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [80]:
character(5)

[1] "" "" "" "" ""

In [81]:
x=c(1,2,3,7)
y=c(2,3,5,1)

In [82]:
x

[1] 1 2 3 7

In [83]:
y

[1] 2 3 5 1

In [84]:
x+y

[1] 3 5 8 8

In [85]:
x-y

[1] -1 -1 -2  6

In [86]:
x * y

[1]  2  6 15  7

In [87]:
x/y

[1] 0.5000000 0.6666667 0.6000000 7.0000000

In [89]:
x + c(10)

[1] 11 12 13 17

In [90]:
x + c(10,10,10,10)

[1] 11 12 13 17

In [91]:
x + c(1,2)

[1] 2 4 4 9

In [92]:
length(x)

[1] 4

In [93]:
c(c(1,2,3,7),c(10))

[1]  1  2  3  7 10

In [94]:
c(c(1,2,3,7),c(10),15,40)

[1]  1  2  3  7 10 15 40

In [95]:
c(c(1,2,3,7),c(10),c(15,40))

[1]  1  2  3  7 10 15 40

In [96]:
height_vec = c(180,169,173)

In [97]:
height_vec

[1] 180 169 173

In [99]:
names(height_vec) = c("Brain","Toby","Sherry")

In [101]:
print( height_vec )

 Brain   Toby Sherry 
   180    169    173 


In [102]:
names(height_vec)

[1] "Brain"  "Toby"   "Sherry"

In [104]:
names(height_vec)[1] = 'Tom'

In [106]:
print(height_vec)

   Tom   Toby Sherry 
   180    169    173 


In [108]:
print( height_vec > 175 )

   Tom   Toby Sherry 
  TRUE  FALSE  FALSE 


In [109]:
print( height_vec == 175 )

   Tom   Toby Sherry 
 FALSE  FALSE  FALSE 


In [110]:
print( height_vec != 175 )

   Tom   Toby Sherry 
  TRUE   TRUE   TRUE 


In [111]:
height_vec[1]

Tom 
180

In [115]:
height_vec[c(1,3)]

Tom Sherry 
   180    173

In [112]:
height_vec['Tom']

Tom 
180

In [113]:
height_vec['Sherry']

Sherry 
   173

In [114]:
height_vec[c('Tom','Sherry')]

Tom Sherry 
   180    173

In [117]:
height_vec[height_vec > 175]

Tom 
180

In [118]:
height_vec[c(T,F,F)]

Tom 
180

In [120]:
height_vec > 170 & height_vec < 175

Tom   Toby Sherry 
 FALSE  FALSE   TRUE

In [121]:
height_vec[height_vec > 170 & height_vec < 175]

Sherry 
   173

In [123]:
height_vec[height_vec < 170 | height_vec > 175]

Tom Toby 
 180  169

In [124]:
#p38 example
h=c(180,169,173)
w=c(73,87,43)

In [126]:
bmi = w/(h/100)^2

In [127]:
names(bmi) = c("Brian","Toby","Sherry")

In [128]:
bmi

Brian     Toby   Sherry 
22.53086 30.46112 14.36734

In [129]:
print( bmi[bmi < 18.5 | bmi >= 24] )

    Toby   Sherry 
30.46112 14.36734 


### seq(),rep(),paste()

In [130]:
?seq

In [131]:
seq(from = 1,to = 20)

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [132]:
seq(from=20,to=1)

[1] 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [133]:
seq(from=1,to=20,by=2)

[1]  1  3  5  7  9 11 13 15 17 19

In [134]:
seq(from=2,to=20,by=2)

[1]  2  4  6  8 10 12 14 16 18 20

In [136]:
seq(from=1,to=20,length.out = 5)

[1]  1.00  5.75 10.50 15.25 20.00

In [137]:
seq(from = 1,to=20,length=5)

[1]  1.00  5.75 10.50 15.25 20.00

In [140]:
for(i in 1:20){
  print(i)    
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20


In [141]:
20:1

[1] 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1

In [142]:
rep(c(1),times=5)

[1] 1 1 1 1 1

In [143]:
?rep

In [144]:
rep(c(1,2),times=5)

[1] 1 2 1 2 1 2 1 2 1 2

In [150]:
rep(c(1,2),times=c(3,4))

[1] 1 1 1 2 2 2 2

In [145]:
rep(c(1,2),each=5)

[1] 1 1 1 1 1 2 2 2 2 2

In [151]:
rep(c(1,2),length.out = 5)

[1] 1 2 1 2 1

In [152]:
rep_len(c(1,2),5)

[1] 1 2 1 2 1

In [153]:
paste("the","big","bang","theory")

[1] "the big bang theory"

In [160]:
paste("the","big","bang","theory",sep='-')

[1] "the-big-bang-theory"

In [161]:
length( paste("the","big","bang","theory",sep='-') )

[1] 1

In [163]:
paste(c("big","bang"),c(1,2),sep='-')

[1] "big-1"  "bang-2"

In [164]:
length( paste(c("big","bang"),c(1,2),sep='-') )

[1] 2

In [166]:
paste(c("big","bang"),c(1,2),sep='-',collapse = ' ')

[1] "big-1 bang-2"

In [167]:
length( paste(c("big","bang"),c(1,2),sep='-',collapse = ' ') )

[1] 1

In [168]:
c(2,T,1+4i,'aaa')

[1] "2"    "TRUE" "1+4i" "aaa"

In [169]:
c(2,T,1+4i)

[1] 2+0i 1+0i 1+4i

In [170]:
c(2,T)

[1] 2 1

In [171]:
?sum

In [176]:
sum(height_vec > 175)

[1] 1

In [177]:
h

[1] 180 169 173

In [178]:
w

[1] 73 87 43

In [179]:
?matrix

In [180]:
matrix(data=c(h,w),byrow=F,nrow=3)

[,1] [,2]
[1,] 180  73  
[2,] 169  87  
[3,] 173  43

In [181]:
kevin = c(85,73)
marry = c(72,64)
jerry = c(59,66)

In [185]:
mat = matrix(data=c(kevin,marry,jerry),byrow=T,nrow=3 )
mat

[,1] [,2]
[1,] 85   73  
[2,] 72   64  
[3,] 59   66

In [187]:
colnames(mat) = c("first","second")

In [188]:
mat

first second
[1,] 85    73    
[2,] 72    64    
[3,] 59    66

In [189]:
rownames(mat) = c('kevin', 'marry', 'jerry')

In [190]:
mat

first second
kevin 85    73    
marry 72    64    
jerry 59    66

In [192]:
class( dim(mat) )

[1] "integer"

In [197]:
dim(mat)[1]

[1] 3

In [198]:
nrow(mat)

[1] 3

In [196]:
dim(mat)[2]

[1] 2

In [199]:
ncol(mat)

[1] 2

In [200]:
t(mat)

kevin marry jerry
first  85    72    59   
second 73    64    66

In [203]:
print(mat[1,])

 first second 
    85     73 


In [204]:
print( mat[c(1,2),] )

      first second
kevin    85     73
marry    72     64


In [205]:
print( mat[,1] )

kevin marry jerry 
   85    72    59 


In [206]:
print(mat[1,1])

[1] 85


In [208]:
print(mat[1:3,1:2])

      first second
kevin    85     73
marry    72     64
jerry    59     66


In [210]:
print( mat['kevin',] )

 first second 
    85     73 


In [211]:
print( mat[c('kevin','jerry'),] )

      first second
kevin    85     73
jerry    59     66


In [212]:
print( mat[,'first'] )

kevin marry jerry 
   85    72    59 


In [213]:
print( mat[,c('first','second')] )

      first second
kevin    85     73
marry    72     64
jerry    59     66


In [217]:
mat[mat[,'first'] >= 60,]

first second
kevin 85    73    
marry 72    64

In [220]:
sam = c(78,63)
rbind(mat,sam)

first second
kevin 85    73    
marry 72    64    
jerry 59    66    
sam   78    63

In [222]:
mat2 = rbind(mat,c(78,63))

In [226]:
rownames(mat2)[nrow(mat2)] = 'sam'

In [228]:
nrow(mat2)

[1] 4

In [229]:
third = c(82,77,70,64)

In [232]:
mat3 = cbind(mat2,third)

In [233]:
mat3

first second third
kevin 85    73     82   
marry 72    64     77   
jerry 59    66     70   
sam   78    63     64

In [234]:
rowSums(mat3)

kevin marry jerry   sam 
  240   213   195   205

In [235]:
rowMeans(mat3)

kevin    marry    jerry      sam 
80.00000 71.00000 65.00000 68.33333

In [236]:
colMeans(mat3)

first second  third 
 73.50  66.50  73.25

In [237]:
m1 = matrix(1:4, byrow=TRUE, nrow=2)
m2 = matrix(5:8, byrow=TRUE, nrow=2)

In [238]:
m1

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [239]:
m2

[,1] [,2]
[1,] 5    6   
[2,] 7    8

In [240]:
m1+m2

[,1] [,2]
[1,]  6    8  
[2,] 10   12

In [241]:
m1-m2

[,1] [,2]
[1,] -4   -4  
[2,] -4   -4

In [242]:
m1*m2

[,1] [,2]
[1,]  5   12  
[2,] 21   32

In [243]:
m1/m2

[,1]      [,2]     
[1,] 0.2000000 0.3333333
[2,] 0.4285714 0.5000000

In [244]:
m1%*%m2

[,1] [,2]
[1,] 19   22  
[2,] 43   50